name: Run main.py and update JSON

on:
  schedule:
    - cron: '0 12 * * *'  # daily at 12:00 UTC
  workflow_dispatch:      # allow manual trigger

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run main.py
        run: python main.py

      - name: Commit and push JSON changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add '*.json'
          git commit -m "Auto-update JSON from main.py" || echo "No changes to commit"
          git push
