name: Run Daily Quran Ayah Delivery System

on:
  schedule:
    - cron: '30 0 * * *'  # Runs every day at 6:00 AM SL Time (UTC+5:30)
  workflow_dispatch:      # Allows manual run

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        persist-credentials: false  # We'll handle push auth explicitly

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python main.py

    - name: Commit and push changes if any
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Show modified files for debug
        git status
        
        # Explicitly add the JSON file
        git add quran_reading_state.json
        
        if ! git diff --cached --quiet; then
          git commit -m "Auto update quran_reading_state.json after daily run"
          git push origin HEAD:main
        else
          echo "No changes to commit."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
